/* DON'T EDIT - This file is generated by running "ONFI_timing.rb" */

#ifndef __INCLUDE_ONFI_TIMING_H
#define __INCLUDE_ONFI_TIMING_H


/*
 * Asynchronous ONFI timing modes
 *  System Clock = 33.33Mhz
 *  Pulse Width  = 30.00300030003ns.
 *
 *                          Mode  0   1   2   3   4   5
 *======================================================*/
static const uint8_t tADL [] = {  7,  4,  4,  4,  3,  3};
static const uint8_t tALH [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tALS [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tAR  [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tCCS [] = {  7,  7,  7,  7,  7,  7};
static const uint8_t tCEA [] = {  4,  2,  1,  1,  1,  1};
static const uint8_t tCH  [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tCHZ [] = {  4,  2,  2,  2,  1,  1};
static const uint8_t tCLH [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tCLR [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tCLS [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tCOH [] = {  0,  1,  1,  1,  1,  1};
static const uint8_t tCS  [] = {  3,  2,  1,  1,  1,  1};
static const uint8_t tDH  [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tDS  [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tIR  [] = {  1,  0,  0,  0,  0,  0};
static const uint8_t tRC  [] = {  4,  2,  2,  1,  1,  1};
static const uint8_t tREA [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tREH [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tRHOH[] = {  0,  1,  1,  1,  1,  1};
static const uint8_t tRHW [] = {  7,  4,  4,  4,  4,  4};
static const uint8_t tRHZ [] = {  7,  7,  4,  4,  4,  4};
static const uint8_t tRLOH[] = {  0,  0,  0,  0,  1,  1};
static const uint8_t tRP  [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tRR  [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tWB  [] = {  7,  4,  4,  4,  4,  4};
static const uint8_t tWC  [] = {  4,  2,  2,  1,  1,  1};
static const uint8_t tWH  [] = {  1,  1,  1,  1,  1,  1};
static const uint8_t tWHR [] = {  4,  3,  3,  2,  2,  2};
static const uint8_t tWP  [] = {  2,  1,  1,  1,  1,  1};
static const uint8_t tWW  [] = {  4,  4,  4,  4,  4,  4};

// Constant values for all modes.
#define tRST_read          166
#define tRST_program       333
#define tRST_erase       16664
#define tRST_power_on      166


#endif  // __INCLUDE_ONFI_TIMING_H
