/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_ONFI_init_ShouldBeOK(void);
extern void test_ONFI_Reset_ShouldWork(void);
extern void test_ONFI_Features_ShouldBeChanged(void);
extern void test_ONFI_set_speed_ShouldWork(void);
extern void test_ReadPage_ShouldDump(void);

static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
      setUp();
      test();
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  tearDown();
  setUp();
}


int main(void)
{
  Unity.TestFile = "tests/NFC/test_dump.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_ONFI_init_ShouldBeOK, 24);
  RUN_TEST(test_ONFI_Reset_ShouldWork, 29);
  RUN_TEST(test_ONFI_Features_ShouldBeChanged, 35);
  RUN_TEST(test_ONFI_set_speed_ShouldWork, 54);
  RUN_TEST(test_ReadPage_ShouldDump, 104);

  UnityEnd();
  return 0;
}
