/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_NFC_init_ShouldBeOK(void);
extern void test_NFC_DMAWFF_ShouldBeOK(void);
extern void test_NFC_DMARFF_ShouldBeOK(void);

static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
      setUp();
      test();
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  tearDown();
  setUp();
}


int main(void)
{
  Unity.TestFile = "tests/NFC/test_NFC.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_NFC_init_ShouldBeOK, 22);
  RUN_TEST(test_NFC_DMAWFF_ShouldBeOK, 27);
  RUN_TEST(test_NFC_DMARFF_ShouldBeOK, 52);

  UnityEnd();
  return 0;
}
