/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

char MessageBuffer[50];

extern void setUp(void);
extern void tearDown(void);

extern void test_memory_ShouldBe32KB(void);
extern void test_ignore_ShouldIgnore(void);
extern void test_fail_ShouldFail(void);

static void runTest(UnityTestFunction test)
{
  if (TEST_PROTECT())
  {
      setUp();
      test();
  }
  if (TEST_PROTECT() && !TEST_IS_IGNORED)
  {
    tearDown();
  }
}
void resetTest()
{
  tearDown();
  setUp();
}


int main(void)
{
  Unity.TestFile = "tests/NFC/test_bed.c";
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_memory_ShouldBe32KB, 23);
  RUN_TEST(test_ignore_ShouldIgnore, 36);
  RUN_TEST(test_fail_ShouldFail, 41);

  UnityEnd();
  return 0;
}
